version: '3.3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: filmestop
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: filmestop
    ports:
      - "8432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://filmestop:1234@db:5432/filmestop


  
